### ISSUE TITLE
`chainsawhudgun` set to zero does not work

### ISSUE THREAD

**Issue by YellowberryHN** [HarpNetStudios/cardboard#35]
disables idle sound, and makes a strange sound instead.

**Comment by garsipal** [comment]
The strange sound is nothing more than `S_PUNCH1`, the default sound for the chainsaw defined in `guninfo`. It sounds weird because the `attackdelay` of the chainsaw was reduced to 10. By setting `chainsawhudgun` to 0 you just disable `attackchan` and `idlechan` but this does not stop the gun (chainsaw) default sound from playing, nor it prevents the engine from rendering the chainsaw hudgun model if I'm not mistaken (this should also happens in Cube 2).

**Comment by YellowberryHN** [comment]
Ah, that does explain that behavior. I feel like it should act slightly differently, I'll have to look into it.

**Comment by YellowberryHN** [comment]
Resolved in https://github.com/HarpNetStudios/cardboard/commit/6dc7a2070a4a2940d781268ac2f74a87e0e85bd5 by removing it entirely, the entire melee weapon code will be reworked anyways.
